name: BuildAndTest


on:
  push:
    branches: ["dev"]
  workflow_call:
  

permissions:
  contents: write


env:
    DOTNET_VERSION: '7.0.x'


jobs:
  build-publish-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: ${{ env.DOTNET_VERSION }}
      - name: Restore dependecies
        run: dotnet restore
      - name: Build
        run: dotnet build --no-restore
      - name: Test
        run: dotnet test --no-build --verbosity normal
      