name: Publish

on:
  push: 
    branches: ["main"]

permissions:
    contents: write


env:
    DOTNET_VERSION: '7.0.x'
    CONFIGURATION: Release
    OUTPUT: release
    PROJECT_NAME: LexerGenerator.Blazor.csproj
    SOLUTION_NAME: LexerGenerator.sln
    REPOSITORY_NAME: LexerGenerator

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Call build_and_test workflow
        uses: LexerGenerator/LexerGenerator/.github/workflows/build_and_test
      - name: Publish
        run: dotnet publish ${{ env.SOLUTION_NAME }} --configuration ${{ env.CONFIGURATION }} --output ${{ env.OUTPUT }}
      - name: Change base-tag in index.html from / to PasswordGenerator_CICD_Test
        run: sed -i 's/<base href="\/" \/>/<base href="\/${{ env.REPOSITORY_NAME }}\/" \/>/g' ${{ env.OUTPUT }}/wwwroot/index.html

      - name: copy index.html to 404.html
        run: cp ${{ env.OUTPUT }}/wwwroot/index.html ${{ env.OUTPUT }}/wwwroot/404.html

      - name: Add .nojekyll file
        run: touch ${{ env.OUTPUT }}/wwwroot/.nojekyll

      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@v4
        with:
         branch: gh-pages
         folder: ${{ env.OUTPUT }}/wwwroot

